spring:
  data:
    mongodb:
      uri : mongodb+srv://martin:${mongodb.password}@cluster0.8u5vj2l.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
      database : InOfficeTracker
  cloud:
    aws:
      parameterstore:
        enabled: true
      region:
        static: ap-southeast-2

mongodb:
  password: ${ssm:/MONGODB_PASSWORD}
