spring:
  config:
    import: "aws-parameterstore:/"
  cloud:
    aws:
      region:
        static: ap-southeast-2
  data:
    mongodb:
      uri: mongodb+srv://martin:${MONGODB_PASSWORD}@cluster0.8u5vj2l.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
      database: InOfficeTracker