name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy-backend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build with Maven
        working-directory: backend
        run: mvn clean package --file pom.xml

      - name: List build artifacts
        run: ls -al backend/target/

      - name: Copy backend jar to EC2
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          source: backend/target/*.jar
          target: ${{ secrets.DEPLOY_DIR }}

      - name: Restart backend service
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          script: |
            cd ${{ secrets.DEPLOY_DIR }}
            sudo systemctl daemon-reload
            sudo systemctl restart in-office-tracker
            sudo systemctl status in-office-tracker --no-pager

  deploy-frontend:
    runs-on: ubuntu-latest
    needs: deploy-backend   # ✅ Wait for backend to finish
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build React frontend
        working-directory: ./frontend/in-office-tracker
        run: |
          npm install
          npm run build

      - name: Ensure frontend deploy directory exists
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          script: |
            sudo mkdir -p ${{ secrets.FRONTEND_DEPLOY_DIR }}
            sudo chown -R $USER:$USER ${{ secrets.FRONTEND_DEPLOY_DIR }}

      - name: Copy frontend build to EC2
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          source: frontend/in-office-tracker/build
          target: ${{ secrets.FRONTEND_DEPLOY_DIR }}

      - name: Reload Nginx
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          script: |
            sudo nginx -t && sudo systemctl reload nginx
